version: '3.1'

services:
  amtb-db:
    image: postgres
    container_name: amtb-db
    restart: always
    environment:
      POSTGRES_DB: amtb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"