DROP TABLE IF EXISTS USER_STATE;

CREATE TABLE USER_STATE
(
    USER_ID  BIGINT,
    STATE_ID SMALLINT
);

ALTER TABLE IF EXISTS USER_STATE
    ADD CONSTRAINT US_USER_ID_BU_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES BOT_USER (BU_ID);
ALTER TABLE IF EXISTS USER_STATE
    ADD CONSTRAINT US_STATE_ID_STATE_ID_FK FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID);